from datetime import date

from a_share_platform.domain.security_master import (
    Board,
    Company,
    Exchange,
    IdentifierHistory,
    IdentifierKind,
    IndustryMembership,
    Listing,
    ListingState,
    ListingStatePeriod,
    Security,
    SecurityClass,
    SecurityMaster,
    SpecialTreatment,
)


def build_security_master_fixture() -> SecurityMaster:
    return SecurityMaster(
        companies=(
            Company("company:cmre", "招商局积余产业运营服务股份有限公司"),
            Company("company:spg", "深圳市物业发展（集团）股份有限公司"),
            Company("company:meidu", "美都能源股份有限公司"),
        ),
        securities=(
            Security("security:cmre:a", "company:cmre", SecurityClass.A_SHARE, "CNY"),
            Security("security:spg:a", "company:spg", SecurityClass.A_SHARE, "CNY"),
            Security("security:spg:b", "company:spg", SecurityClass.B_SHARE, "HKD"),
            Security("security:meidu:a", "company:meidu", SecurityClass.A_SHARE, "CNY"),
        ),
        listings=(
            Listing(
                "listing:cmre:xshe",
                "security:cmre:a",
                Exchange.XSHE,
                Board.MAIN,
                date(1994, 9, 28),
            ),
            Listing(
                "listing:spg-a:xshe",
                "security:spg:a",
                Exchange.XSHE,
                Board.MAIN,
                date(1992, 3, 30),
            ),
            Listing(
                "listing:spg-b:xshe",
                "security:spg:b",
                Exchange.XSHE,
                Board.MAIN,
                date(1992, 3, 30),
            ),
            Listing(
                "listing:meidu:xshg",
                "security:meidu:a",
                Exchange.XSHG,
                Board.MAIN,
                date(1999, 4, 8),
                date(2020, 8, 14),
            ),
        ),
        identifiers=(
            IdentifierHistory(
                "listing:cmre:xshe",
                IdentifierKind.CODE,
                "000043",
                date(1994, 9, 28),
                date(2019, 12, 16),
                "a_share_mcp_baostock",
            ),
            IdentifierHistory(
                "listing:cmre:xshe",
                IdentifierKind.CODE,
                "001914",
                date(2019, 12, 16),
                None,
                "a_share_mcp_baostock",
            ),
            IdentifierHistory(
                "listing:cmre:xshe",
                IdentifierKind.NAME,
                "中航善达",
                date(2018, 1, 1),
                date(2019, 12, 16),
                "a_share_mcp_baostock",
            ),
            IdentifierHistory(
                "listing:cmre:xshe",
                IdentifierKind.NAME,
                "招商积余",
                date(2019, 12, 16),
                None,
                "a_share_mcp_baostock",
            ),
            IdentifierHistory(
                "listing:spg-a:xshe",
                IdentifierKind.CODE,
                "000011",
                date(1992, 3, 30),
                None,
                "contract_fixture",
            ),
            IdentifierHistory(
                "listing:spg-a:xshe",
                IdentifierKind.NAME,
                "深物业A",
                date(1992, 3, 30),
                None,
                "contract_fixture",
            ),
            IdentifierHistory(
                "listing:spg-b:xshe",
                IdentifierKind.CODE,
                "200011",
                date(1992, 3, 30),
                None,
                "contract_fixture",
            ),
            IdentifierHistory(
                "listing:spg-b:xshe",
                IdentifierKind.NAME,
                "深物业B",
                date(1992, 3, 30),
                None,
                "contract_fixture",
            ),
            IdentifierHistory(
                "listing:meidu:xshg",
                IdentifierKind.CODE,
                "600175",
                date(1999, 4, 8),
                date(2020, 8, 14),
                "a_share_mcp_baostock",
            ),
            IdentifierHistory(
                "listing:meidu:xshg",
                IdentifierKind.NAME,
                "退市美都",
                date(2020, 5, 20),
                date(2020, 8, 14),
                "a_share_mcp_baostock",
            ),
        ),
        states=(
            ListingStatePeriod(
                "listing:cmre:xshe",
                date(1994, 9, 28),
                None,
                ListingState.ACTIVE,
                SpecialTreatment.NONE,
                "contract_fixture",
            ),
            ListingStatePeriod(
                "listing:spg-a:xshe",
                date(1992, 3, 30),
                None,
                ListingState.ACTIVE,
                SpecialTreatment.NONE,
                "contract_fixture",
            ),
            ListingStatePeriod(
                "listing:spg-b:xshe",
                date(1992, 3, 30),
                None,
                ListingState.ACTIVE,
                SpecialTreatment.NONE,
                "contract_fixture",
            ),
            ListingStatePeriod(
                "listing:meidu:xshg",
                date(2020, 5, 20),
                date(2020, 5, 28),
                ListingState.ACTIVE,
                SpecialTreatment.STAR_ST,
                "a_share_mcp_baostock",
            ),
            ListingStatePeriod(
                "listing:meidu:xshg",
                date(2020, 5, 28),
                date(2020, 6, 29),
                ListingState.SUSPENDED,
                SpecialTreatment.STAR_ST,
                "a_share_mcp_baostock",
            ),
            ListingStatePeriod(
                "listing:meidu:xshg",
                date(2020, 6, 29),
                date(2020, 8, 14),
                ListingState.ACTIVE,
                SpecialTreatment.NONE,
                "a_share_mcp_baostock",
            ),
            ListingStatePeriod(
                "listing:meidu:xshg",
                date(2020, 8, 14),
                None,
                ListingState.TERMINATED,
                SpecialTreatment.NONE,
                "a_share_mcp_baostock",
            ),
        ),
        industries=(
            IndustryMembership(
                "security:cmre:a",
                "CSRC",
                "K70",
                "房地产业",
                date(2018, 1, 1),
                date(2019, 12, 16),
                "a_share_mcp_baostock",
            ),
            IndustryMembership(
                "security:cmre:a",
                "CSRC",
                "K72",
                "商务服务业",
                date(2019, 12, 16),
                None,
                "contract_fixture",
            ),
        ),
    )
