// Generated by platform/scripts/export_openapi.py. Do not edit manually.
export type DataMode = 'current_research' | 'strict_historical';
export type DeploymentStage = 'research' | 'shadow' | 'paper' | 'limited_live';

export interface ResponseContext {
  as_of: string;
  system_as_of: string;
  data_mode: DataMode;
  deployment_stage: DeploymentStage;
  trust_state: string | null;
  dataset_version_ids: string[];
  model_version_ids: string[];
  run_id: string | null;
  coverage: Record<string, unknown>;
  warnings: string[];
}

export interface Envelope<T = unknown> {
  data: T;
  context: ResponseContext;
}

export interface ProblemDetails {
  type: string;
  title: string;
  status: number;
  detail: string;
  instance: string;
}

export interface ReadOperation {
  responses: { 200: { content: { 'application/json': Envelope } } };
}

export interface paths {
  "/api/artifacts": { get: ReadOperation };
  "/api/calendars/{exchange}/next-session": { get: ReadOperation };
  "/api/capabilities": { get: ReadOperation };
  "/api/companies/{company_id}": { get: ReadOperation };
  "/api/datasets": { get: ReadOperation };
  "/api/health": { get: ReadOperation };
  "/api/identity": { get: ReadOperation };
  "/api/listings/resolve": { get: ReadOperation };
  "/api/market-data/bars": { get: ReadOperation };
  "/api/market-data/corporate-actions": { get: ReadOperation };
  "/api/market-data/quality": { get: ReadOperation };
  "/api/market-data/summary": { get: ReadOperation };
  "/api/runs": { get: ReadOperation };
  "/api/securities": { get: ReadOperation };
  "/api/system/catalog": { get: ReadOperation };
  "/api/system/disclosures": { get: ReadOperation };
  "/api/system/evidence/{raw_object_id}": { get: ReadOperation };
  "/api/system/facts/compare": { get: ReadOperation };
  "/api/system/facts/revisions": { get: ReadOperation };
  "/api/system/jobs": { get: ReadOperation };
  "/api/system/lineage": { get: ReadOperation };
  "/api/system/mismatches": { get: ReadOperation };
  "/api/system/quality": { get: ReadOperation };
  "/api/universes": { get: ReadOperation };
  "/api/universes/{universe_version_id}/coverage": { get: ReadOperation };
  "/api/universes/{universe_version_id}/diff": { get: ReadOperation };
  "/api/universes/{universe_version_id}/snapshot": { get: ReadOperation };
  "/api/version": { get: ReadOperation };
}
