"""Repository port for the immutable governance ledger."""

from __future__ import annotations

from typing import Protocol

from a_share_platform.domain.governance import Artifact, DatasetVersion, LineageEdge, RunRecord


class DatasetVersionRepository(Protocol):
    def register_dataset(self, value: DatasetVersion) -> DatasetVersion: ...

    def list_datasets(self) -> tuple[DatasetVersion, ...]: ...


class GovernanceRepository(DatasetVersionRepository, Protocol):

    def register_run(self, value: RunRecord) -> RunRecord: ...

    def get_run(self, run_id: str) -> RunRecord | None: ...

    def append_run_state(self, value: RunRecord) -> RunRecord: ...

    def list_runs(self) -> tuple[RunRecord, ...]: ...

    def register_artifact(self, value: Artifact) -> Artifact: ...

    def list_artifacts(self) -> tuple[Artifact, ...]: ...

    def register_lineage(self, value: LineageEdge) -> LineageEdge: ...

    def list_lineage(self) -> tuple[LineageEdge, ...]: ...
